### ISSUE TITLE
SSR whitespace warning and graphql-tools dependecies

### ISSUE THREAD

**Issue by webular** [apollostack/saturn#41] opened 2016-09-07 11:23 UTC
> Warning: render(): Target node has markup rendered by React, but there are unrelated nodes as well. This is most commonly caused by white-space inserted around server-rendered markup.

Whats the best way to get rid of this?  This shows up for me in the console after `saturn create app-name` ,  `npm install` & finally `saturn dev`

**Comment by tmeasday** [comment] 2016-09-08 00:10
This is an issue with `react-apollo`'s `renderToStringWithData` (https://github.com/apollostack/saturn/blob/devel/app/server.js#L106). I think it's either just been fixed or will be fixed soon. We should update saturn to 0.5.2

**Closed** 2016-09-15 08:53 UTC

**Comment by ads1018** [comment] 2016-10-12 14:08
Anyone know if this has been resolved in react-apollo?

**Comment by tmeasday** [comment] 2016-10-12 23:17
I thought I fixed this with a saturn release. What are you seeing @ads1018 ?

**Comment by ads1018** [comment] 2016-10-13 03:09
I'm seeing the same warning as @webular when I run `npm run dev`:

`warning.js:36 Warning: render(): Target node has markup rendered by React, but there are unrelated nodes as well. This is most commonly caused by white-space inserted around server-rendered markup.` 

I'm using the latest version of Saturn.

**Comment by tmeasday** [comment] 2016-10-13 03:26
@ads1018 can you see what the difference in markup is (if you view source + compare to the current DOM tree)? Is it an extra `<script>` tag in the `<div id="content">`?

**Comment by ads1018** [comment] 2016-10-13 03:39
I am seeing an extra `script` tag inside `<div id="content">`...

**Comment by tmeasday** [comment] 2016-10-13 03:41
And you are definitely on `react-apollo@0.4.15` or higher?

**Comment by tmeasday** [comment] 2016-10-13 03:42
Oh interesting, maybe that should have been 0.5.0... https://github.com/apollostack/react-apollo/releases/tag/v0.5.0

**Comment by ads1018** [comment] 2016-10-13 03:46
Ah my bad yeah I was actually _not_ on the latest version of react-apollo after all. Updating to the latest fixed my issue. Thanks @tmeasday!
