### ISSUE TITLE
Saturn is still using 'apollo-client/gql' which now deprecated

### ISSUE THREAD

**Issue by ads1018** [apollostack/saturn#19] opened 2016-07-17 23:28 UTC
I noticed an out of date dependency while building. 'apollo-client/gql' is deprecated...should be using 'graphql-tag'

**Comment by TimMikeladze** [comment] 2016-07-17 23:42
Duplicate of issue #14, see PR #16 for the fix.

**Closed** 2016-07-20 02:13 UTC
